### ISSUE TITLE
Call Blue Mesa about reservations

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/communitydinner-feb2016#1]

**Comment by 01parkelly** [comment]
http://www.bluemesagrill.com/locations/

One in addison? or plano? Addison on seems like a little bit closer?
btw we are reserving table for 20 people?

**Comment by uxutd** [comment]
Sorry meant to ask you on Slack just now - you're right the one in Addison
is closer, so that sounds good to me.

I think 20 is the max we've had at previous dinners, but I'm wondering if
we should go up to 25 since turnout was high at the kickoff.

**Comment by 01parkelly** [comment]
called Blue Meas in Addison, and they said they have a long cocktail table, which can fit 20 people. 
So I made a reservation for 20-25people on Thursday 2/18 at 6:30 pm.

No discount, though :( Manager said no discount at that location.

Also, happy hour is from 4 - 7:30 pm, but quesadilla bar?! is only until 6:30 pm.

Let me know if you guys have any other thoughts?

**Comment by linamoon** [comment]
Restaurant has been reserved by @01parkelly. Closing issue.
